### ISSUE TITLE
SVG output + explorer = math processing errors

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#119]
I see this failure at http://codepen.io/pkra/pen/yOWrWQ (with the dist built from current master).

Also, only one expression (the first display-style expression) has the usual `Math processing error` in the DOM.

lastError gives

```javascript
MathJax.Hub.lastError
TypeError: Cannot read property 'root' of null
    at Object.AddSpeech (https://beta.mathjax.org/mathjax/contrib/a11y/Assistive-Explore.js?rev=2.6.1:1:5904)
    at Object.AddEvent (https://beta.mathjax.org/mathjax/contrib/a11y/Assistive-Explore.js?rev=2.6.1:1:5825)
    at Object.Register (https://beta.mathjax.org/mathjax/contrib/a11y/Assistive-Explore.js?rev=2.6.1:1:4595)
    at Function.execute (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:3084)
    at cb (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:2661)
    at Execute (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:7293)
    at ExecuteHooks (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:10599)
    at Function.execute (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:3084)
    at cb (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:2661)
    at Execute (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:7293)
    at Post (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:9345)
    at Object.processOutput (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:40062)
    at Function.execute (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:3084)
    at Function.WAITEXECUTE (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:5827)
    at cb (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:2661)
    at Function.WAITEXECUTE (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:6016)
    at cb (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:2661)
    at Execute (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:7293)
    at Object.loadComplete (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full:19:15890)
    at https://cdn.mathjax.org/mathjax/2.6-latest/jax/output/SVG/fonts/TeX/Main/Regular/BasicLatin.js?rev=2.6.1:19:19138
```

Switching to a different renderer + refreshing the page resets ok.

**Comment by dpvc** [comment]
It turns out that this is due to a bug in the `getJaxForMath()` method of the SVG renderer.  It has to check if an element has class name `MathJax_SVG_Display`, but while the math is being processed (part of the equation chunking), the class name is `MathJax_SVG_Display MathJax_Processing`.  The `MathJax_Processing` is removed when the chunk is displayed, so most of the time when `getJaxFromMath()` is used, this works.  But because the explorer responds to `New Math` signals immediately, and this occurs while the math is still not displayed, when the explorer tries to look up the jax for the math, the test fails.

I will fix it, but it isn an upstream bug, not a RespEq one.

**Comment by dpvc** [comment]
This is resolved in the `respeq119` branch of my fork of MathJax.

**Comment by pkra** [comment]
Fixed.

**Comment by pkra** [comment]
I'm still seeing this problem (using the copy on the beta CDN)

**Comment by zorkow** [comment]
I think it is a timing issue. The patch in explorer.js never gets called.

**Comment by pkra** [comment]
Yes. Maybe it needs to go into the menu to load right away?

**Comment by dpvc** [comment]
@zorkow, make sure you have the SVG renderer selected.  It does get triggered for me.  I have been out this morning, but will take a loot at it.

**Comment by dpvc** [comment]
> Maybe it needs to go into the menu to load right away?

No, it needs to be part of explorer, since that can be loaded separately.

**Comment by dpvc** [comment]
OK, I fixed it. I was using `apply()` where I should have used `call()`.  Argh!

**Comment by zorkow** [comment]
JAXFROMMATH does that

I was just writing that up.

**Comment by pkra** [comment]
Yay! Thanks, guys.

**Comment by pkra** [comment]
Pushed to CDN. All clear!
